// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	api_layer "cloudwego-api-gateway/pkg/API-Layer/biz/router/api/layer"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	api_layer.Register(r)
}
