// Code generated by hertz generator.

package layer

import (
	"context"
	"fmt"

	layer "github.com/iksars/cloudwego-api-gateway/pkg/API-Layer/biz/model/api/layer"
	routing "github.com/iksars/cloudwego-api-gateway/pkg/routing"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

var routingHandler routing.RouteHandler = routing.NewDefaultRouteHandler()

// GateWayMethod .
// @router /agw [POST]
func GateWayMethod(ctx context.Context, c *app.RequestContext) {
	var err error
	var req layer.LayReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	fmt.Println(req.ServiceName)
	fmt.Println(req.ServiceMethod)

	//这里调用routing层的RoutingDistribute方法
	cli := routingHandler.RoutingDistribute(req.ServiceName)

	reqBytes, err := c.Body()
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp, err := cli.GenericCall(ctx, req.ServiceMethod, string(reqBytes))
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	c.JSON(consts.StatusOK, resp)
}
