// Code generated by hertz generator.

package layer

import (
	"context"
	"fmt"

	layer "cloudwego-api-gateway/pkg/API-Layer/biz/model/api/layer"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// GateWayMethod .
// @router /agw [POST]
func GateWayMethod(ctx context.Context, c *app.RequestContext) {
	var err error
	var req layer.LayReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	fmt.Println(req.ServiceName)
	fmt.Println(req.ServiceMethod)
	fmt.Println(c.Body())

	//这里调用routing层的RoutingDistribute方法

	resp := new(layer.LayResp)

	resp.RespBody = "hello agw"

	c.JSON(consts.StatusOK, resp)
}
