// Code generated by hertz generator.

package layer

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _gatewaymethodMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _agwMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _nameMw() []app.HandlerFunc {
	// your code...
	return nil
}
