// Code generated by hertz generator.

package IDLManage

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _addbynameMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletebynameMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _downloadbynameMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _selectallMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _selectbynameMw() []app.HandlerFunc {
	// your code...
	return nil
}
