// Code generated by hertz generator.

package IDLManage

import (
	"context"

	IDLManage "cloudwego-api-gateway/pkg/IDL-Management/hertz-back/biz/model/IDLManage"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// SelectAll .
// @router /api/getAll [GET]
func SelectAll(ctx context.Context, c *app.RequestContext) {
	var err error
	var req IDLManage.QueryAllReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(IDLManage.QueryResp)

	c.JSON(consts.StatusOK, resp)
}

// SelectByName .
// @router /api/search [GET]
func SelectByName(ctx context.Context, c *app.RequestContext) {
	var err error
	var req IDLManage.NameBasedReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(IDLManage.QueryResp)

	c.JSON(consts.StatusOK, resp)
}

// AddByName .
// @router /api/add [POST]
func AddByName(ctx context.Context, c *app.RequestContext) {
	var err error
	var req IDLManage.AddReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(IDLManage.CommonResp)

	c.JSON(consts.StatusOK, resp)
}

// DeleteByName .
// @router /api/delete [DELETE]
func DeleteByName(ctx context.Context, c *app.RequestContext) {
	var err error
	var req IDLManage.NameBasedReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(IDLManage.CommonResp)

	c.JSON(consts.StatusOK, resp)
}

// DownloadByName .
// @router /api/download [GET]
func DownloadByName(ctx context.Context, c *app.RequestContext) {
	var err error
	var req IDLManage.NameBasedReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(IDLManage.CommonResp)

	c.JSON(consts.StatusOK, resp)
}
